### PR TITLE
V1.0.0 CU-5wt3mp commands base structure

### PR DESCRIPTION
**Pull request by Gum-Joe**
This PR adds the base structure for commands, that is discrete chunks of logic that are shared by the CLI and GUI.

~~The main focus here is to create @twokeys/commandex, which helps generate command factories from our commands so that they are all in one place and instance of TwoKeys objects can easily be passed through to commands without having to manually create an instance every time a command is called.~~

The main focus of this PR is to create the base structure that will allow us to write both stateless and stateful commands in @twokeys/common-hi (see `@twokeys/common-hi/src/common/`), as well as run them using a custom TwoKeys object provided by the GUI or CLI.

### CODE REVIEW

**Comment by Gum-Joe** [comment]
Task linked: [CU-5wt3mp Commands: base structure](https://app.clickup.com/t/5wt3mp)

**Comment by Gum-Joe** [comment]
Note to reviewer: DO NOT MEREG THIS if commandex package is still there.  Also don't merge if checks are failing ofc

**Comment by Gum-Joe** [comment]
Note: I've decided not to export everything in `index.ts`, given how much is in this dir, please require directories directly.

If the reviewer disagrees with this, please mark this in `src/index.ts`

**Comment by ILikeTeaALot** [comment]
> 
> 
> Note: I've decided not to export everything in `index.ts`, given how much is in this dir, please require directories directly.
> 
> If the reviewer disagrees with this, please mark this in `src/index.ts`

this is ok by me!

**Pull request merged**
